# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting cocoapods performance.
# To disable it, uncomment the following line.
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Release' => :release,
  'Profile' => :profile,
}

def flutter_root
  # Support FLUTTER_ROOT from the environment if it exists (very reliable on Codemagic)
  return ENV['FLUTTER_ROOT'] if ENV['FLUTTER_ROOT']

  generated_xcode_build_settings_path = File.expand_path(File.join('Flutter', 'Generated.xcconfig'))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get has been executed."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/\AFLUTTER_ROOT=(.*)\z/)
    return matches[1] if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get."
end

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Required for some plugins compatibility with latest iOS
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
